// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seswrpyynbrquurnonss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlc3dycHl5bmJycXV1cm5vbnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDA4MDMsImV4cCI6MjA3MzQxNjgwM30._wnpaziYtbuXEdTQCCRKMas9PmQ6iqHBNXPLYzNWK_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});